### ISSUE TITLE
Negitive Spinner Values

### ISSUE THREAD

**Issue by poing** [kayecandy/surveyform#1]
Spinners should **not** allow negative values.

<img width="409" alt="Screen Shot 2019-06-19 at 10 16 53" src="https://user-images.githubusercontent.com/11417007/59729952-7c90ae00-927b-11e9-87da-cd6f3a66b5a8.png">

**Comment by kayecandy** [comment]
Done

![image](https://user-images.githubusercontent.com/5698031/59747413-6c90c280-92ab-11e9-951d-6db9aa33d15f.png)

**Comment by kayecandy** [comment]
Done

![image](https://user-images.githubusercontent.com/5698031/59747413-6c90c280-92ab-11e9-951d-6db9aa33d15f.png)
