### ISSUE TITLE
Survey ID: Autogenerated

### ISSUE THREAD

**Issue by poing** [kayecandy/surveyform#13]
The user will never enter the survey ID, it's an auto-generated value.  *You can generate anything for the demo.*

<img width="455" alt="Screen Shot 2019-06-21 at 11 04 06" src="https://user-images.githubusercontent.com/11417007/59892553-7c77e600-9414-11e9-8014-de08ba77cf16.png">

**Comment by kayecandy** [comment]
Done
![image](https://user-images.githubusercontent.com/5698031/60020329-6727e380-96c2-11e9-9238-070c68c98d30.png)
