### ISSUE TITLE
Hangup Audio: Optional

### ISSUE THREAD

**Issue by poing** [kayecandy/surveyform#14]
The hangup audio *should* be optional.

<img width="464" alt="Screen Shot 2019-06-21 at 11 05 48" src="https://user-images.githubusercontent.com/11417007/59892578-9c0f0e80-9414-11e9-9de3-84d80b2c2759.png">

**Comment by kayecandy** [comment]
Done
![image](https://user-images.githubusercontent.com/5698031/60019834-6478be80-96c1-11e9-9094-46468b42c1a2.png)
