### ISSUE TITLE
Description: Optional

### ISSUE THREAD

**Issue by poing** [kayecandy/surveyform#16]
Description *should* be optional.

<img width="427" alt="Screen Shot 2019-06-21 at 11 15 08" src="https://user-images.githubusercontent.com/11417007/59892887-e5139280-9415-11e9-9fe3-823f06ade56e.png">

**Comment by kayecandy** [comment]
Done

![image](https://user-images.githubusercontent.com/5698031/60019675-077d0880-96c1-11e9-8457-872720edf96d.png)
