### ISSUE TITLE
Basic Details

### ISSUE THREAD

**Issue by poing** [kayecandy/surveyform#17]
The modification screen for the basic details is **fine**.

<img width="936" alt="Screen Shot 2019-06-21 at 11 21 50" src="https://user-images.githubusercontent.com/11417007/59893137-de394f80-9416-11e9-8892-be98d0510518.png">

But is *does not* make sense to show the files **first** in the *minimized* version.

<img width="45%" alt="Screen Shot 2019-06-21 at 11 23 45" src="https://user-images.githubusercontent.com/11417007/59893191-1e003700-9417-11e9-9ae6-ac544b977863.png">&nbsp;&nbsp;&nbsp;<img width="45%" alt="Screen Shot 2019-06-21 at 11 24 00" src="https://user-images.githubusercontent.com/11417007/59893190-1d67a080-9417-11e9-9b38-18aeef17e1de.png">

The minimized version would look better with the form fields at the top.  Have to scroll to see the entries.

**Comment by kayecandy** [comment]
A few changes for this:

1. I made the entire Basic Details area a dropzone. This is true for expanded and collapsed mode
![Screenshot from 2019-06-24 23-23-14](https://user-images.githubusercontent.com/5698031/60031404-46b65400-96d7-11e9-94f1-b9388b71b800.png)

2. I also put it at the bottom as per your suggestion and changed the appearance of the uploaded files
![Screenshot from 2019-06-24 23-23-26](https://user-images.githubusercontent.com/5698031/60031451-5df54180-96d7-11e9-9567-f87d16325457.png)
