### ISSUE TITLE
Created Date

### ISSUE THREAD

**Issue by poing** [kayecandy/surveyform#2]
The created date should not be editable.  *Default* should be `today()` or `now()`.  It can be `disabled` even `hidden`.  *Was only used on the current site, to balance the number of elements.*

<img width="410" alt="Screen Shot 2019-06-19 at 10 19 12" src="https://user-images.githubusercontent.com/11417007/59730055-ec9f3400-927b-11e9-8679-7dda889bbf2e.png">

**Comment by kayecandy** [comment]
Right now, I set it to `disabled` that defaults to `now()`.

![image](https://user-images.githubusercontent.com/5698031/59740821-cc7f6d00-929b-11e9-99f1-abc0a66217fe.png)
This is how it looks like hidden.

Let me know which you prefer
