### ISSUE TITLE
Date Format YYYY-MM-DD

### ISSUE THREAD

**Issue by poing** [kayecandy/surveyform#3]
The date format *should* be `YYYY-MM-DD`

<img width="410" alt="Screen Shot 2019-06-19 at 10 19 12" src="https://user-images.githubusercontent.com/11417007/59730080-0771a880-927c-11e9-98d7-c9ea34233855.png">

**Comment by kayecandy** [comment]
![image](https://user-images.githubusercontent.com/5698031/59743214-26833100-92a2-11e9-9b89-a0f1bdb177cc.png)


Done
