### ISSUE TITLE
Timeout Slider

### ISSUE THREAD

**Issue by poing** [kayecandy/surveyform#5]
Can you make the timeout slider a *little more* detailed?

<img width="421" alt="Screen Shot 2019-06-19 at 10 24 13" src="https://user-images.githubusercontent.com/11417007/59730206-6f27f380-927c-11e9-98ac-07f14a629423.png">

---

Here's how the current timeout slider works, you can see the code [here](https://gist.github.com/poing/869bc167e9e927fb237a66d30c4af055).

<img width="45%" alt="Screen Shot 2019-06-19 at 10 27 26" src="https://user-images.githubusercontent.com/11417007/59730312-db0a5c00-927c-11e9-89dc-91a10db4e33c.png"><img width="45%" alt="Screen Shot 2019-06-19 at 10 27 16" src="https://user-images.githubusercontent.com/11417007/59730313-db0a5c00-927c-11e9-833f-ff092d4a2326.png">

**Comment by kayecandy** [comment]
Done. I downloaded your code, plugged it in the page and skinned the timer to fit the theme.

![image](https://user-images.githubusercontent.com/5698031/59751438-17f14580-92b3-11e9-8d5f-aed069264ef9.png)
