### ISSUE TITLE
Trunk and Channels

### ISSUE THREAD

**Issue by poing** [kayecandy/surveyform#6]
The trunk `value` *should* set the `max` for the channel slider.  I *suggest* having the drop-down options use `10,25,50,100` for the demo.

<img width="834" alt="Screen Shot 2019-06-19 at 10 31 14" src="https://user-images.githubusercontent.com/11417007/59730450-64219300-927d-11e9-98f8-087de18e7319.png">

---

Here's the [code](https://gist.github.com/poing/6e15b60f29b6ba7b100bddc03b9e84cc) and some examples from the current site.  *So you have an idea how it currently works.*

<img width="45%" alt="Screen Shot 2019-06-19 at 10 32 35" src="https://user-images.githubusercontent.com/11417007/59730549-c4183980-927d-11e9-966f-6f0b583b1eca.png"><img width="45%" alt="Screen Shot 2019-06-19 at 10 35 54" src="https://user-images.githubusercontent.com/11417007/59730636-122d3d00-927e-11e9-9d49-cfa93b0717f2.png">

----

<img width="45%" alt="Screen Shot 2019-06-19 at 10 33 22" src="https://user-images.githubusercontent.com/11417007/59730547-c37fa300-927d-11e9-8bb2-fd121537adf6.png"><img width="45%" alt="Screen Shot 2019-06-19 at 10 33 10" src="https://user-images.githubusercontent.com/11417007/59730548-c37fa300-927d-11e9-8635-1490af6d7280.png">

**Comment by kayecandy** [comment]
Done. I took the code and plugged it in the page. I just had to change the json url

![image](https://user-images.githubusercontent.com/5698031/59796554-5cf79500-9310-11e9-8be0-e1e6559fc129.png)

---
I also created a temporary json file to remain consistent with the code
![image](https://user-images.githubusercontent.com/5698031/59796660-929c7e00-9310-11e9-989d-266dfc2dc03f.png)
