### ISSUE TITLE
Response Tracking Question: Deafult

### ISSUE THREAD

**Issue by poing** [kayecandy/surveyform#7]
The response tracking question, should *default* to the last question.  *Users only change it, when they want to count the results based on a different question.*

<img width="414" alt="Screen Shot 2019-06-19 at 10 40 51" src="https://user-images.githubusercontent.com/11417007/59730841-e2cb0000-927e-11e9-9b44-ac87c3ebb084.png">

**Comment by kayecandy** [comment]
![image](https://user-images.githubusercontent.com/5698031/59740581-17e54b80-929b-11e9-94a5-657304d364fa.png)
Done
